version: '3.8'
services:
  api:
    build: .
    #ports:
    #  - 3000:3000
    env_file:
     - .env
    environment: 
      - PORT=3000
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=3000
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`127.0.0.1`)
      - traefik.http.middlewares.api-strip-prefix.stripprefix.prefixes=/dev
      - traefik.http.routers.app-http.middlewares=api-strip-prefix@docker
  reverse-proxy:
    image: traefik:v2.4
    ports:
      - 80:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --accesslog
      - --log


  #nginx:
  #  depends_on:
  #    - api
  #  image: nginx:alpine
  #  volumes: 
  #    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #  ports:
  #    - 80:80
