---
swagger: "2.0"
info:
  version: "2021-03-03T03:59:29Z"
  title: "mtr-hk-dev-api-gateway"
host: "api-dev.mtrdatastudio.com"
schemes:
- "https"
paths:
  /ingest/info:
    get:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "422":
          description: "422 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "401":
          description: "401 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "502":
          description: "502 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "403":
          description: "403 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "404":
          description: "404 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "504":
          description: "504 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      security:
      - api_key: []
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /ingest/{project}/{dataset}:
    get:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      parameters:
      - name: "dataset"
        in: "path"
        required: true
        type: "string"
      - name: "project"
        in: "path"
        required: true
        type: "string"
      - name: "date"
        in: "query"
        required: true
        type: "string"
      - name: "source"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "422":
          description: "422 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "401":
          description: "401 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "502":
          description: "502 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "403":
          description: "403 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "404":
          description: "404 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "504":
          description: "504 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /ingest/{project}/{dataset}/{file-name}/{file-format}/{year}/{month}/{day}:
    delete:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      parameters:
      - name: "dataset"
        in: "path"
        required: true
        type: "string"
      - name: "file-name"
        in: "path"
        required: true
        type: "string"
      - name: "day"
        in: "path"
        required: true
        type: "string"
      - name: "project"
        in: "path"
        required: true
        type: "string"
      - name: "file-format"
        in: "path"
        required: true
        type: "string"
      - name: "year"
        in: "path"
        required: true
        type: "string"
      - name: "month"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "422":
          description: "422 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "401":
          description: "401 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "502":
          description: "502 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "403":
          description: "403 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "404":
          description: "404 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "504":
          description: "504 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /ingest/{project}/{dataset}/{file-name}/{file-format}/{year}/{month}/{day}/{method}:
    post:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      parameters:
      - name: "dataset"
        in: "path"
        required: true
        type: "string"
      - name: "file-name"
        in: "path"
        required: true
        type: "string"
      - name: "day"
        in: "path"
        required: true
        type: "string"
      - name: "project"
        in: "path"
        required: true
        type: "string"
      - name: "file-format"
        in: "path"
        required: true
        type: "string"
      - name: "method"
        in: "path"
        required: true
        type: "string"
      - name: "year"
        in: "path"
        required: true
        type: "string"
      - name: "month"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "422":
          description: "422 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "401":
          description: "401 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "502":
          description: "502 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "403":
          description: "403 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "404":
          description: "404 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "504":
          description: "504 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      security:
      - api_key: []
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /query/info:
    get:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "422":
          description: "422 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "401":
          description: "401 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "502":
          description: "502 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "403":
          description: "403 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "404":
          description: "404 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "504":
          description: "504 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      security:
      - api_key: []
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /query/{database}/{table}:
    get:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      parameters:
      - name: "database"
        in: "path"
        required: true
        type: "string"
      - name: "where"
        in: "query"
        required: true
        type: "string"
      - name: "table"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "422":
          description: "422 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "500":
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "401":
          description: "401 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "502":
          description: "502 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "403":
          description: "403 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "404":
          description: "404 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "504":
          description: "504 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      security:
      - api_key: []
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
